environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: https://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\extra\\appveyor\\run_with_compiler.cmd"

  matrix:

    # Pre-installed Python versions, which Appveyor may upgrade to
    # a later point release.
    # See: https://www.appveyor.com/docs/installed-software#python

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"
      WINDOWS_SDK_VERSION: "v7.1"
      TOXENV: "3.6-unit"

    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "64"
      WINDOWS_SDK_VERSION: "v7.1"
      TOXENV: "3.7-unit"

    - PYTHON: "C:\\Python38-x64"
      PYTHON_VERSION: "3.8.x"
      PYTHON_ARCH: "64"
      WINDOWS_SDK_VERSION: "v7.1"
      TOXENV: "3.8-unit"


init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "powershell extra\\appveyor\\install.ps1"
  - "%PYTHON%/python -m pip install -U pip setuptools tox"
  - "%PYTHON%/Scripts/pip.exe install -U eventlet"
  - "%PYTHON%/Scripts/pip.exe install -U -r requirements/extras/thread.txt"

build: off

test_script:
  - "%WITH_COMPILER% %PYTHON%/Scripts/tox -v -- -v"

after_test:
  - "%WITH_COMPILER% %PYTHON%/python setup.py bdist_wheel"

artifacts:
  - path: dist\*

cache:
  - '%LOCALAPPDATA%\pip\Cache'

#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse
